/*
//	File:	TLBID.h
//
//	Author:	Trias
//
//	Date:	16-Jun-2003
//
//	Defines IDs used by the TLB plug-in.
//
//	ADOBE SYSTEMS INCORPORATED
//	Copyright 2003 Trias Developpement. All rights reserved.
//	
//	NOTICE: Adobe permits you to use, modify, and distribute this file in
//	accordance with the terms of the Adobe license agreement accompanying it.
//	If you have received this file from a source other than Adobe, then your
//	use, modification, or distribution of it requires the prior written
//	permission of Adobe.
//
*/

#ifndef __TLBID_h__
#define __TLBID_h__

#include "SDKDef.h"


// Plug-in:
#define kTLBPluginName	"TextLib"			// Name of this plug-in.
#define kTLBPrefixNumber	0xd0489		// Unique prefix number for this plug-in(*Must* be obtained from Adobe Developer Support).
// Plug-in version string. Pulled from the shared TriasVersion.h header so
// every Trias plug-in bumps in lock-step. Edit Gaia\TriasVersion.h to
// change the family-wide version.
#include "../../../Gaia/TriasVersion.h"
#define kTLBVersion			kTriasVersionString			// Version of this plug-in (for the About Box).
#define kTLBAuthor			"Trias"			// Author of this plug-in (for the About Box).

// Plug-in Prefix: (please change kTLBPrefixNumber above to modify the prefix.)
#define kTLBPrefix		RezLong(kTLBPrefixNumber)				// The unique numeric prefix for all object model IDs for this plug-in.
#define kTLBStringPrefix	SDK_DEF_STRINGIZE(kTLBPrefixNumber)	// The string equivalent of the unique prefix number for  this plug-in.

// PluginID:
DECLARE_PMID(kPlugInIDSpace, kTLBPluginID, kTLBPrefix + 0)

// ClassIDs:
DECLARE_PMID(kClassIDSpace, kTextHelperBoss, kTLBPrefix + 0)

// InterfaceIDs:
DECLARE_PMID(kInterfaceIDSpace, IID_ISTYLEHELPER, kTLBPrefix + 0)
DECLARE_PMID(kInterfaceIDSpace, IID_ITXTATTRHELPER, kTLBPrefix + 1)

// ImplementationIDs:
DECLARE_PMID(kImplementationIDSpace, kTLBStyleHelperImpl, kTLBPrefix + 0)
DECLARE_PMID(kImplementationIDSpace, kTLBTxtAttrHelperImpl,	kTLBPrefix + 1)

// String keys
#define kTlbNilInterface kTLBStringPrefix "kTlbNilInterface"	
#define kTlbNilParameter kTLBStringPrefix "kTlbNilParameter"
#define kNewStyleCmdFailed kTLBStringPrefix "kNewStyleCmdFailed"
#define kDefaultStyleCmdFailed kTLBStringPrefix "kDefaultStyleCmdFailed"
#define kEditStyleCmdFailed kTLBStringPrefix "kEditStyleCmdFailed"
#define kErrLanguageNotDefined kTLBStringPrefix "kErrLanguageNotDefined"

// Initial data format version numbers
#define kTLBFirstMajorFormatNumber  kSDKDef_30_PersistMajorVersionNumber
#define kTLBFirstMinorFormatNumber  kSDKDef_30_PersistMinorVersionNumber

// Data format version numbers for the PluginVersion resource 
#define kTLBCurrentMajorFormatNumber kTLBFirstMajorFormatNumber // most recent major format change
#define kTLBCurrentMinorFormatNumber kTLBFirstMinorFormatNumber // most recent minor format change

#endif // __TLBID_h__
//  Generated by Dolly build 17: template "IfPanelMenu".
// End, TLBID.h.


