/*
//	File:	PMUFactoryList.h
//
//	Author: Wilfried LEFEVRE
//
//	Date:	11-Jun-2003
//
//	Each C++ implementation class in the plug-in and its corresponding ImplementationID
//	should be registered in this file.
//
//	ADOBE SYSTEMS INCORPORATED
//	Copyright 2003 Trias Developpement. All rights reserved.
//	
//	NOTICE: Adobe permits you to use, modify, and distribute this file in
//	accordance with the terms of the Adobe license agreement accompanying it.
//	If you have received this file from a source other than Adobe, then your
//	use, modification, or distribution of it requires the prior written
//	permission of Adobe.
//
*/

REGISTER_PMINTERFACE(PMUActionComponent, kPMUActionComponentImpl)
REGISTER_PMINTERFACE(PMUPanelWidgetObserver, kPMUPanelWidgetObserverImpl)
REGISTER_PMINTERFACE(PMUDialogController, kPMUDialogControllerImpl)
REGISTER_PMINTERFACE(PMUDialogController, kPMUDialogObserverImpl)
REGISTER_PMINTERFACE(PMUDocPathDialogController, kPMUDocPathDialogControllerImpl)
REGISTER_PMINTERFACE(PMUDocPathDialogObserver, kPMUDocPathDialogObserverImpl)
REGISTER_PMINTERFACE(PMUImageSettingDialogController, kPMUImageSettingDialogControllerImpl)
REGISTER_PMINTERFACE(PMUImageSettingDialogObserver, kPMUImageSettingDialogObserverImpl)
REGISTER_PMINTERFACE(PMUExportPrefsDialogController, kPMUExportPrefsDialogControllerImpl)
REGISTER_PMINTERFACE(PMUTypeRefDialogController, kPMUTypeRefDialogControllerImpl)
REGISTER_PMINTERFACE(PMUStartupShutdown, kPMUStartupShutdownImpl)
REGISTER_PMINTERFACE(PMUSetUpComposerPaletteCmd, kPMUSetUpComposerPaletteCmdImpl)
REGISTER_PMINTERFACE(PMUButtonTips, kPMUButtonTipsImpl)
//  Generated by Dolly build 17: template "IfPanelMenu".
// End, PMUFactoryList.h.

