/*
//	File:	PrsFactoryList.h
//
//	Author: Wilfried LEFEVRE
//
//	Date:	11-Jun-2003
//
//	Each C++ implementation class in the plug-in and its corresponding ImplementationID
//	should be registered in this file.
//
//	ADOBE SYSTEMS INCORPORATED
//	Copyright 2003 Trias Developpement. All rights reserved.
//	
//	NOTICE: Adobe permits you to use, modify, and distribute this file in
//	accordance with the terms of the Adobe license agreement accompanying it.
//	If you have received this file from a source other than Adobe, then your
//	use, modification, or distribution of it requires the prior written
//	permission of Adobe.
//
*/

#include "GlobalDefs.h"

REGISTER_PMINTERFACE(PrsTCLReader,kPrsTCLReaderImpl)
REGISTER_PMINTERFACE(PrsTCLParser,kPrsTCLParserImpl)
REGISTER_PMINTERFACE(PrsTCLReferencesListPersist, kPrsTCLReferencesListPersistImpl)
REGISTER_PMINTERFACE(PrsTCLReferencesList, kPrsTCLReferencesListImpl)
REGISTER_PMINTERFACE(PrsSetDocTCLReferencesList, kPrsSetDocTCLReferencesListImpl)
REGISTER_PMINTERFACE(ParserSuiteASB, kPrsSuiteASBImpl)
REGISTER_PMINTERFACE(ParserSuiteLayoutCSB, kPrsSuiteLayoutCSBImpl)
REGISTER_PMINTERFACE(PrsDeleteCleanup, kPrsDeleteCleanupImpl)
REGISTER_PMINTERFACE(PermRefsTag, kPermRefsTagImpl)
REGISTER_PMINTERFACE(PrsReverseTCL, kPrsReverseTCLImpl)
REGISTER_PMINTERFACE(PrsTCLWriter, kPrsTCLWriterImpl)
REGISTER_PMINTERFACE(PermRefsTagReport, kPermRefsTagReportImpl)
REGISTER_PMINTERFACE(PermRefsTagTextAdornment, kPermRefsTagTextAdornmentImpl)
REGISTER_PMINTERFACE(PrsTCLAdornmentShape, kPrsTCLAdornmentShapeImpl)
REGISTER_PMINTERFACE(PermRefsSuiteASB, kPermRefsSuiteASBImpl)
REGISTER_PMINTERFACE(PermRefsSuiteTextCSB, kPermRefsSuiteTextCSBImpl)
REGISTER_PMINTERFACE(PrsPreferencesPersist, kPrsPreferencesPersistImpl)
REGISTER_PMINTERFACE(PrsPreferences, kPrsPreferencesImpl)
REGISTER_PMINTERFACE(PrsSetPreferencesCmd, kPrsSetPreferencesCmdImpl)
REGISTER_PMINTERFACE(PrsRespService, kPrsRespServiceImpl)
REGISTER_PMINTERFACE(PrsCustomServiceProvider, kPrsCustomServiceProviderImpl)
REGISTER_PMINTERFACE(PrsScriptProvider, kPrsScriptProviderImpl)
REGISTER_PMINTERFACE(PrsErrorStringService, kPrsErrorStringServiceImpl)
REGISTER_PMINTERFACE(PrsRegistration, kPrsRegistrationImpl)
REGISTER_PMINTERFACE(PrsRegistrationPersist, kPrsRegistrationPersistImpl)
REGISTER_PMINTERFACE(PrsSetRegistrationInfoCmd, kPrsSetRegistrationInfoCmdImpl)
REGISTER_PMINTERFACE(PrsStartupShutdown, kPrsStartupShutdownImpl)
REGISTER_PMINTERFACE(PrsEpsExportPrefsPersist, kPrsEpsExportPrefsPersistImpl)
REGISTER_PMINTERFACE(PrsEpsExportPrefs, kPrsEpsExportPrefsImpl)
REGISTER_PMINTERFACE(PrsEpsDocumentNamePersist, kPrsEpsDocumentNamePersistImpl)
REGISTER_PMINTERFACE(PrsEpsDocumentName, kPrsEpsDocumentNameImpl)
REGISTER_PMINTERFACE(PrsSetDocEpsExportPrefsCmd, kPrsSetDocEpsExportPrefsCmdImpl)
REGISTER_PMINTERFACE(PrsSetDocPdfExportPrefsCmd, kPrsSetDocPdfExportPrefsCmdImpl)
REGISTER_PMINTERFACE(PrsSetImageInfosCmd, kPrsSetImageInfosCmdImpl)
REGISTER_PMINTERFACE(PermRefsTextEditPreProcess, kPermRefsTextEditPreProcessImpl)
REGISTER_PMINTERFACE(PermRefsTextEditPostProcess, kPermRefsTextEditPostProcessImpl)
REGISTER_PMINTERFACE(PrsInsertTextCmd, kPrsInsertTextCmdImpl)
REGISTER_PMINTERFACE(PrsWideStringData, kPrsWideStringDataImpl)
REGISTER_PMINTERFACE(PrsTCLRefScriptProvider, kPrsTCLRefScriptProviderImpl)
REGISTER_PMINTERFACE(PrsPasteImportItemObserver, kPrsPasteImportItemObserverImpl)
REGISTER_PMINTERFACE(PrsSetTCLRefDataCmd, kPrsSetTCLRefDataCmdImpl)
REGISTER_PMINTERFACE(PrsParserThread, kPrsParserThreadImpl)
REGISTER_PMINTERFACE(PrsSetTOPPositionCmd, kPrsSetTOPPositionCmdImpl)

#if AUTO_TAGGING
	REGISTER_PMINTERFACE(PrsLastPremRefPersist,		kPrsLastPremRefPersistImpl)
	REGISTER_PMINTERFACE(PrsLastPremRefCmd,			kPrsLastPremRefCmdImpl)
	REGISTER_PMINTERFACE(PrsLastPremRef,			kPrsLastPremRefImpl)
	REGISTER_PMINTERFACE(PermRefsTag1TextAdornment, kPermRefsTag1TextAdornmentImpl)
	REGISTER_PMINTERFACE(PermRefsTag2TextAdornment, kPermRefsTag2TextAdornmentImpl)
#endif

#if !SERVER
REGISTER_PMINTERFACE(PrsEnterSerialNumberCmd, kPrsEnterSerialNumberCmdImpl)
REGISTER_PMINTERFACE(PrsSerialNumberDialogController, kPrsSerialNumberDialogControllerImpl)
#endif

//  Generated by Dolly build 17: template "IfPanelMenu".
// End, PrsFactoryList.h.

