/*
//	File:	PrsScriptingDefs.h
//
//	Author:	Trias
//
//	Date:	23/11/2005
//
*/

#ifndef __PrsScriptingDefs_h__
#define __PrsScriptingDefs_h__



//#define kCPrefs_CLSID { 0x8d448fe0, 0x8194, 0x11d3, { 0xa6, 0x53, 0x0, 0xe0, 0x98, 0x71, 0xa, 0x6f } }
//DECLARE_GUID(CPrefs_CLSID, kCPrefs_CLSID);

// Note: 4-char IDs below must be unique.
// See ScriptingDefs.h for further information.

// Event IDs
#define	e_ExecuteTCLFile 'etcl'
#define e_GetPermRefs 'gref'

#define p_Ref 'pref'
#define p_FileName 'pfil'

// Properties/Parameters IDs
#define p_TCLRef 'pRef'
#define p_PermRefTag 'pTag'

#endif // __PrsScriptingDefs_h__

//  Code generated by DollyXs code generator
