/*
//
//	File:	TriggerResourceDeps.cpp
//
//	Author: Wilfried LEFEVRE
//
//	Date:	11-Jun-2003
//
//	Ensures the application is relinked when the .fr file has been recompiled.
//
//	ADOBE SYSTEMS INCORPORATED
//	Copyright 2003 Trias Developpement. All rights reserved.
//	
//	NOTICE: Adobe permits you to use, modify, and distribute this file in
//	accordance with the terms of the Adobe license agreement accompanying it.
//	If you have received this file from a source other than Adobe, then your
//	use, modification, or distribution of it requires the prior written
//	permission of Adobe.
//
*/

#include "VCPlugInHeaders.h"

#include "Prs.fr"

//  Generated by Dolly build 17: template "IfPanelMenu".
// End, TriggerResourceDeps.cpp.


