/*
//	File:	FLBFactoryList.h
//
//	Author: Wilfried LEFEVRE
//
//	Date:	16-Jun-2003
//
//	Each C++ implementation class in the plug-in and its corresponding ImplementationID
//	should be registered in this file.
//
//	ADOBE SYSTEMS INCORPORATED
//	Copyright 2003 Trias Developpement. All rights reserved.
//	
//	NOTICE: Adobe permits you to use, modify, and distribute this file in
//	accordance with the terms of the Adobe license agreement accompanying it.
//	If you have received this file from a source other than Adobe, then your
//	use, modification, or distribution of it requires the prior written
//	permission of Adobe.
//
*/

REGISTER_PMINTERFACE(FLBItemManager,kFLBItemManagerImpl)
REGISTER_PMINTERFACE(FLBItemTransform,kFLBItemTransformImpl)
REGISTER_PMINTERFACE(FLBTextFrameHelper,kFLBTextFrameHelperImpl)
//  Generated by Dolly build 17: template "IfPanelMenu".
// End, FLBFactoryList.h.

