/*
//	File:	FLBID.cpp
//
//	Author: Trias
//
//	Date:	16-Jun-2003
//
//	Makes your IDs available as named symbols in the Debug build.
//
//	ADOBE SYSTEMS INCORPORATED
//	Copyright 2003 Trias Developpement. All rights reserved.
//	
//	NOTICE: Adobe permits you to use, modify, and distribute this file in
//	accordance with the terms of the Adobe license agreement accompanying it.
//	If you have received this file from a source other than Adobe, then your
//	use, modification, or distribution of it requires the prior written
//	permission of Adobe.
//
*/

#include "VCPlugInHeaders.h"

// General includes:
#include "ShuksanID.h"
#include "IDFactory_cpp.h"

#pragma export on
	#include "FLBID.h"
#pragma export off
//  Generated by Dolly build 17: template "IfPanelMenu".
// End, FLBID.cpp.

