/*
//	File:	DLBID.h
//
//	Author:	Trias
//
//	Date:	16-Jun-2003
//
//	Defines IDs used by the DLB plug-in.
//
//	ADOBE SYSTEMS INCORPORATED
//	Copyright 2003 Trias Developpement. All rights reserved.
//	
//	NOTICE: Adobe permits you to use, modify, and distribute this file in
//	accordance with the terms of the Adobe license agreement accompanying it.
//	If you have received this file from a source other than Adobe, then your
//	use, modification, or distribution of it requires the prior written
//	permission of Adobe.
//
*/

#ifndef __DLBID_h__
#define __DLBID_h__

#include "SDKDef.h"

// Plug-in:
#define kDLBPluginName		"DocLib"					// Name of this plug-in.
#define kDLBPrefixNumber	0xd047E 					// Unique prefix number for this plug-in(*Must* be obtained from Adobe Developer Support).
// Plug-in version string. Pulled from the shared TriasVersion.h header so
// every Trias plug-in bumps in lock-step. Edit Gaia\TriasVersion.h to
// change the family-wide version.
#include "../../../Gaia/TriasVersion.h"
#define kDLBVersion			kTriasVersionString					// Version of this plug-in (for the About Box).
#define kDLBAuthor			"Trias"			// Author of this plug-in (for the About Box).

// Plug-in Prefix: (please change kDLBPrefixNumber above to modify the prefix.)
#define kDLBPrefix			RezLong(kDLBPrefixNumber)				// The unique numeric prefix for all object model IDs for this plug-in.
#define kDLBStringPrefix	SDK_DEF_STRINGIZE(kDLBPrefixNumber)	// The string equivalent of the unique prefix number for  this plug-in.

// PluginID:
DECLARE_PMID(kPlugInIDSpace, kDLBPluginID, kDLBPrefix + 0)

// ClassIDs:
DECLARE_PMID(kClassIDSpace, kDocHelperBoss,	kDLBPrefix + 0)

// InterfaceIDs:
DECLARE_PMID(kInterfaceIDSpace, IID_IDOCHELPER, kDLBPrefix + 0)
// None in this plug-in.

// ImplementationIDs:
DECLARE_PMID(kImplementationIDSpace, kDLBDocHelperImpl, kDLBPrefix + 0)

// String keys
#define kDlbNilInterface kDLBStringPrefix "kDlbNilInterface"
#define kNewDocCmdFailed kDLBStringPrefix "kNewDocCmdFailed"
#define kSetDocNameCmdFailed kDLBStringPrefix "kSetDocNameCmdFailed"
#define kNewWinCmdFailed kDLBStringPrefix "kNewWinCmdFailed"
#define kCloseWinCmdFailed kDLBStringPrefix "kCloseWinCmdFailed"
#define kDlbNilParameter kDLBStringPrefix "kDlbNilParameter"
#define kSetPageSizeCmdFailed kDLBStringPrefix "kSetPageSizeCmdFailed"
#define kSetMarginCmdFailed kDLBStringPrefix "kSetMarginCmdFailed"
#define kSetColumnCmdFailed kDLBStringPrefix "kSetColumnCmdFailed"
#define kErrImpossibleToSave kDLBStringPrefix "kErrImpossibleToSave"
#define kErrDocNotFound kDLBStringPrefix "kErrDocNotFound"

// Initial data format version numbers
#define kDLBFirstMajorFormatNumber  kSDKDef_30_PersistMajorVersionNumber
#define kDLBFirstMinorFormatNumber  kSDKDef_30_PersistMinorVersionNumber

// Data format version numbers for the PluginVersion resource 
#define kDLBCurrentMajorFormatNumber kDLBFirstMajorFormatNumber // most recent major format change
#define kDLBCurrentMinorFormatNumber kDLBFirstMinorFormatNumber // most recent minor format change
 
#endif // __DLBID_h__
//  Generated by Dolly build 17: template "IfPanelMenu".
// End, DLBID.h.


