//========================================================================================
//  
//  $File: $
//  
//  Owner: Wilfried Lefevre
//  
//  $Author: $
//  
//  $DateTime: $
//  
//  $Revision: $
//  
//  $Change: $
//  
//  Copyright Adobe Systems Incorporated. All rights reserved.
//  
//  NOTICE:  Adobe permits you to use, modify, and distribute this file in accordance 
//  with the terms of the Adobe license agreement accompanying it.  If you have received
//  this file from a source other than Adobe, then your use, modification, or 
//  distribution of it requires the prior written permission of Adobe.
//  
//========================================================================================

//  Code generated by DollyXs code generator
REGISTER_PMINTERFACE(XRailStartupShutdown, kXRLStartupShutdownImpl)
REGISTER_PMINTERFACE(XRailResponder, kXRLResponderImpl)
REGISTER_PMINTERFACE(XRailServiceProvider, kXRLServiceProviderImpl)

REGISTER_PMINTERFACE(XRailDataPersist, kXRLDataPersistImpl)
REGISTER_PMINTERFACE(XRailPrefsDataPersist, kXRLPrefsDataPersistImpl)

REGISTER_PMINTERFACE(XRailSetDocDataCmd, kXRLSetPageSlugDataCmdImpl)
REGISTER_PMINTERFACE(XRailSetPrefsCmd, kXRLSetPrefsCmdImpl)

REGISTER_PMINTERFACE(XRailSetMakePreviewCmd, kXRLSetMakePreviewCmdImpl)
REGISTER_PMINTERFACE(XRLResaPubList, kXRLResaPubListImpl)
REGISTER_PMINTERFACE(XRailSetResaPubListCmd, kXRLSetResaPubListCmdImpl)

REGISTER_PMINTERFACE(XRLAutoClosingDialog, kXRLAutoClosingDialogImpl)
REGISTER_PMINTERFACE(XRLScriptProvider,	kXRLScriptProviderImpl)
