//========================================================================================
//  
//  $File: $
//  
//  Owner: Trias Developpement
//  
//  $Author: $
//  
//  $DateTime: $
//  
//  $Revision: $
//  
//  $Change: $
//  
//  Copyright Adobe Systems Incorporated. All rights reserved.
//  
//  NOTICE:  Adobe permits you to use, modify, and distribute this file in accordance 
//  with the terms of the Adobe license agreement accompanying it.  If you have received
//  this file from a source other than Adobe, then your use, modification, or 
//  distribution of it requires the prior written permission of Adobe.
//  
//========================================================================================
REGISTER_PMINTERFACE(XPGPageMgrAccessor,				kXPageMgrAccessorImpl)
REGISTER_PMINTERFACE(XPGPointerData,					kXPGPointerDataImpl)
REGISTER_PMINTERFACE(XPGXMLMatchingFileHandler,			kXPGXMLMatchingFileHandlerImpl) 
REGISTER_PMINTERFACE(XPGTextImportHandler,				kXPGTextImportHandlerImpl)
REGISTER_PMINTERFACE(XPGSetTagToStyleMapCmd,			kXPGSetTagToStyleMapCmdImpl)
REGISTER_PMINTERFACE(XPGTagToStyleMap,					kXPGTagToStyleMapImpl)
// Removed (dead code): XPGFileSystemImageModel.cpp was deleted. The
// XRail image model is registered below as kXPGXRailImageModelImpl.
//   REGISTER_PMINTERFACE(XPGXRailImageModel, kXPGFileSystemImageModelImpl)
REGISTER_PMINTERFACE(XPageSuiteASB,						kXPGSuiteASBImpl)
REGISTER_PMINTERFACE(XPageSuiteTextCSB,					kXPGTextCSBImpl)
REGISTER_PMINTERFACE(XPageSuiteLayoutCSB,				kXPGLayoutCSBImpl)
REGISTER_PMINTERFACE(XPGXMLLoadTagHandler,				kXPGXMLLoadTagHandlerImpl) 
REGISTER_PMINTERFACE(XPGXMLParserArticle,				kXPGXMLParserArticleImpl) 
REGISTER_PMINTERFACE(XPGStartupShutdown,				kXPGStartupShutdownImpl)
REGISTER_PMINTERFACE(XPGSetArticleIDCmd,				kXPGSetArticleIDCmdImpl)
REGISTER_PMINTERFACE(XPGXMLImageDescriptionHandler,		kXPGXMLImageDescriptionHandlerImpl) 
REGISTER_PMINTERFACE(PersistStringListData,				kPersistStringListDataImpl)
REGISTER_PMINTERFACE(XPGFileSystemFormeModel,			kXPGFileSystemFormeModelImpl)
REGISTER_PMINTERFACE(XPGImportSnippetObserver,			kXPGImportSnippetObserverImpl)
REGISTER_PMINTERFACE(XPGLSIDData,						kXPGLSIDDataPersistImpl)
REGISTER_PMINTERFACE(XPGPreferences,					kXPGPreferencesImpl)
REGISTER_PMINTERFACE(XPGExportArtResp,					kXPGExportArtRespImpl)
REGISTER_PMINTERFACE(XPGXRailImageModel,				kXPGXRailImageModelImpl)
REGISTER_PMINTERFACE(XPGXMLFormeDescriptionHandler,		kXPGXMLFormeDescriptionHandlerImpl) 
REGISTER_PMINTERFACE(XPGXMLArticleDescription,			kXPGXMLArticleDescriptionImpl) 
REGISTER_PMINTERFACE(XPGSetStringCmd,					kXPGSetStringCmdImpl)
REGISTER_PMINTERFACE(XPGUpdateArticleXMLFileCmd,		kXPGUpdateArticleXMLFileCmdImpl)
REGISTER_PMINTERFACE(XPGScriptProvider,			        kXPGScriptProviderImpl)
REGISTER_PMINTERFACE(XPGFormeData,						kXPGFormeDataImpl)
REGISTER_PMINTERFACE(XPGSetFormeDataCmd,				kXPGSetFormeDataCmdImpl)
REGISTER_PMINTERFACE(XPGErrorStringService,				kXPGErrorStringServiceImpl)
REGISTER_PMINTERFACE(XPGFilterStyleCmd,				    kXPGFilterStyleCmdImpl)
REGISTER_PMINTERFACE(XPGSaveAssignmentCmd,				kXPGSaveAssignmentCmdImpl)
REGISTER_PMINTERFACE(XPGXMLExportFileHandler,			kXPGXMLExportFileHandlerImpl) 
REGISTER_PMINTERFACE(XPGUnlockStoriesCmd,				kXPGUnlockStoriesCmdImpl)
REGISTER_PMINTERFACE(XPGResponder,						kXPGResponderImpl)
REGISTER_PMINTERFACE(XPGServiceProvider,				kXPGServiceProviderImpl)
REGISTER_PMINTERFACE(XPageIndexSuiteASB,				kXPGIndexSuiteASBImpl)
REGISTER_PMINTERFACE(XPageIndexSuiteTextCSB,			kXPGIndexSuiteTextCSBImpl)
REGISTER_PMINTERFACE(XPGIAMServiceProvider,				kXPGIAMServiceProviderImpl)
REGISTER_PMINTERFACE(XPGArticleData,					kXPGArticleDataImpl)
REGISTER_PMINTERFACE(XPGSetArticleDataCmd,				kXPGSetArticleDataCmdImpl)
REGISTER_PMINTERFACE(XPGTextData,						kXPGTextDataImpl)
REGISTER_PMINTERFACE(XPGXMLMatchingStylesListHandler,	kXPGXMLMatchingStylesListHandlerImpl) 
REGISTER_PMINTERFACE(XPGKeyValueData,					kXPGKeyValueDataImpl)
REGISTER_PMINTERFACE(XPGXMLMatchingFileHandler2,		kXPGXMLMatchingFileHandler2Impl) 
REGISTER_PMINTERFACE(XPGSetPlacedArticleDataCmd,		kXPGSetPlacedArticleDataCmdImpl)
REGISTER_PMINTERFACE(XPGPlacedArticleData,				kXPGPlacedArticleDataImpl)
REGISTER_PMINTERFACE(XPGDocObserver,					kXPGDocObserverImpl)
REGISTER_PMINTERFACE(XPGXMLPostImportIterationBase,		kXPGXMLPostImportIterationBaseImpl)
REGISTER_PMINTERFACE(XPGCheckTextImportHandler,			kXPGCheckTextImportHandlerImpl) 
REGISTER_PMINTERFACE(XPGArticleSizerCmd,				kXPGArticleSizerCmdImpl)
REGISTER_PMINTERFACE(XPageUtils,						kXPGUtilsImpl)
REGISTER_PMINTERFACE(XPGFileSystemAssemblageModel,		kXPGFileSystemAssemblageModelImpl)
REGISTER_PMINTERFACE(XPGXArticleDataModel,				kXPGArticleDataModelImpl)



//  Code generated by DollyXs code generator
