/*
//	File:	XPGScriptingDefs.h
//
//	Author:	Trias Developpement
//
//	Date:	14/04/2008
//
*/

#ifndef __XPGScriptingDefs_h__
#define __XPGScriptingDefs_h__

//#include "ScriptingWindowDefs.h"

// Note: 4-char IDs below must be unique.
// See ScriptingDefs.h for further information.

// Properties/Parameters IDs
#define p_FormeData 'fxpg'
#define p_PlacedArticleData 'axpg'
#define p_ArticleData 'sxpg'

#endif // __XPGScriptingDefs_h__

//  Code generated by DollyXs code generator
