//========================================================================================
//  
//  $File: $
//  
//  Owner: Trias
//  
//  $Author: $
//  
//  $DateTime: $
//  
//  $Revision: $
//  
//  $Change: $
//  
//  Copyright 1997-2005 Adobe Systems Incorporated. All rights reserved.
//  
//  NOTICE:  Adobe permits you to use, modify, and distribute this file in accordance 
//  with the terms of the Adobe license agreement accompanying it.  If you have received
//  this file from a source other than Adobe, then your use, modification, or 
//  distribution of it requires the prior written permission of Adobe.
//  
//========================================================================================

//  Code generated by DollyXs code generator
REGISTER_PMINTERFACE(XRailChangeStateDialogController, kXRLUIChangeStateDialogControllerImpl)
REGISTER_PMINTERFACE(XRailLinkerDialogController, kXRLUILinkerDialogControllerImpl)
REGISTER_PMINTERFACE(XRailLoginDialogController, kXRLUILoginDialogControllerImpl)
REGISTER_PMINTERFACE(XRailDialogController, kXRLUIDialogControllerImpl)
REGISTER_PMINTERFACE(XRailOpenLoginDialogCmd, kXRLUIOpenLoginDialogCmdImpl)
REGISTER_PMINTERFACE(XRailActionComponent, kXRLUIActionComponentImpl)
REGISTER_PMINTERFACE(XRailUIStartupShutdown, kXRLUIUIStartupShutdownImpl)
REGISTER_PMINTERFACE(XRLUIIntList, kXRLUIIntListImpl)
REGISTER_PMINTERFACE(XRLUILinkerDialogObserver, kXRLUILinkerDialogObserverImpl)
// Commentaires palette (Window > Gaia > Commentaires).
REGISTER_PMINTERFACE(XRLUICommentList,					kXRLUICommentListImpl)
REGISTER_PMINTERFACE(XRLUICommentsPanelObserver,		kXRLUICommentsPanelObserverImpl)
REGISTER_PMINTERFACE(XRLUICommentsTVHierarchyAdapter,	kXRLUICommentsTVHierarchyAdapterImpl)
REGISTER_PMINTERFACE(XRLUICommentsTVWidgetMgr,			kXRLUICommentsTVWidgetMgrImpl)
REGISTER_PMINTERFACE(XRLUICommentsNodeEH,				kXRLUICommentsNodeEHImpl)
