/*
//	File:	PLBFactoryList.h
//
//	Author: Nicolas METAYE
//
//	Date:	28-Oct-2003
//
//	Each C++ implementation class in the plug-in and its corresponding ImplementationID
//	should be registered in this file.
//
//	ADOBE SYSTEMS INCORPORATED
//	Copyright 2003 Adobe Systems Incorporated. All rights reserved.
//	
//	NOTICE: Adobe permits you to use, modify, and distribute this file in
//	accordance with the terms of the Adobe license agreement accompanying it.
//	If you have received this file from a source other than Adobe, then your
//	use, modification, or distribution of it requires the prior written
//	permission of Adobe.
//
*/

REGISTER_PMINTERFACE(PLBPageHelper,kPLBPageHelperImpl)
//  Generated by Dolly build 17: template "IfPanelMenu".
// End, PLBFactoryList.h.

