/*
//	File:	PLBID.h
//
//	Author:	Trias
//
//	Date:	28-Oct-2003
//
//	Defines IDs used by the PLB plug-in.
//
//	ADOBE SYSTEMS INCORPORATED
//	Copyright 2003 Trias Developpement. All rights reserved.
//	
//	NOTICE: Adobe permits you to use, modify, and distribute this file in
//	accordance with the terms of the Adobe license agreement accompanying it.
//	If you have received this file from a source other than Adobe, then your
//	use, modification, or distribution of it requires the prior written
//	permission of Adobe.
//
*/

#ifndef __PLBID_h__
#define __PLBID_h__

#include "SDKDef.h"

// Plug-in:
#define kPLBPluginName		"PageLib"					// Name of this plug-in.
#define kPLBPrefixNumber	0xd0493 					// Unique prefix number for this plug-in(*Must* be obtained from Adobe Developer Support).
// Plug-in version string. Pulled from the shared TriasVersion.h header so
// every Trias plug-in bumps in lock-step. Edit Gaia\TriasVersion.h to
// change the family-wide version.
#include "../../../Gaia/TriasVersion.h"
#define kPLBVersion			kTriasVersionString			// Version of this plug-in (for the About Box).
#define kPLBAuthor			"Trias"			// Author of this plug-in (for the About Box).

// Plug-in Prefix: (please change kDLBPrefixNumber above to modify the prefix.)
#define kPLBPrefix		RezLong(kPLBPrefixNumber)				// The unique numeric prefix for all object model IDs for this plug-in.
#define kPLBStringPrefix	SDK_DEF_STRINGIZE(kPLBPrefixNumber)	// The string equivalent of the unique prefix number for  this plug-in.

// PluginID:
DECLARE_PMID(kPlugInIDSpace, kPLBPluginID, kPLBPrefix + 0)

// ClassIDs:
DECLARE_PMID(kClassIDSpace, kPageHelperBoss,	kPLBPrefix + 0)

// InterfaceIDs:
DECLARE_PMID(kInterfaceIDSpace, IID_IPAGEHELPER, kPLBPrefix + 0)
// None in this plug-in.

// ImplementationIDs:
DECLARE_PMID(kImplementationIDSpace, kPLBPageHelperImpl, kPLBPrefix + 0)

// String keys
#define kPlbNilInterface kPLBStringPrefix "kPlbNilInterface"
#define kPlbNilParameter kPLBStringPrefix "kPlbNilParameter"
#define kNewPageCmdFailed kPLBStringPrefix "kNewPageCmdFailed"
#define kNewSectionCmdFailed kPLBStringPrefix "kNewSectionCmdFailed"
#define kDeletePageCmdFailed kPLBStringPrefix "kDeletePageCmdFailed"
#define kApplyMasterCmdFailed kPLBStringPrefix "kApplyMasterCmdFailed"
#define kSelectPageCmdFailed kPLBStringPrefix "kSelectPageCmdFailed"
#define kErrInvalidMaster kPLBStringPrefix "kErrInvalidMaster"
#define kErrInvalidPages kPLBStringPrefix "kErrInvalidPages"
#define kErrInvalidBasedOn kPLBStringPrefix "kErrInvalidBasedOn"
#define kNewMasterCmdFailed kPLBStringPrefix "kNewMasterCmdFailed"


// Initial data format version numbers
#define kPLBFirstMajorFormatNumber  kSDKDef_30_PersistMajorVersionNumber
#define kPLBFirstMinorFormatNumber  kSDKDef_30_PersistMinorVersionNumber

// Data format version numbers for the PluginVersion resource 
#define kPLBCurrentMajorFormatNumber kPLBFirstMajorFormatNumber // most recent major format change
#define kPLBCurrentMinorFormatNumber kPLBFirstMinorFormatNumber // most recent minor format change

 
#endif // __PLBID_h__
//  Generated by Dolly build 17: template "IfPanelMenu".
// End, PLBID.h.



