/*
//	File:	PLBNoStrip.cpp
//
//	Date:	28-Oct-2003
//
//	ADOBE SYSTEMS INCORPORATED
//	Copyright 2003 Adobe Systems Incorporated. All rights reserved.
//	
//	NOTICE: Adobe permits you to use, modify, and distribute this file in
//	accordance with the terms of the Adobe license agreement accompanying it.
//	If you have received this file from a source other than Adobe, then your
//	use, modification, or distribution of it requires the prior written
//	permission of Adobe.
//
*/

#include "VCPlugInHeaders.h"

#include "InterfaceFactory.h"

extern bool16 gFalse;

/** DontDeadStrip
	references all implementations to stop the compiler dead stripping them from the executable image.
	@author Nicolas METAYE
*/
void DontDeadStrip();

void DontDeadStrip()
{
	if (gFalse)
	{
#include "PLBFactoryList.h"		
	}
}

//  Generated by Dolly build 17: template "IfPanelMenu".
// End, PLBNoStrip.cpp.


